add chess implementation
Scaleup-Excellenteam/exercise-1-chess-SalehNaamneh pull request #1
Opened 2024-06-16 09:33 UTC by SalehNaamneh

2024-07-08 06:17 UTC, excellenteam-scaleup requested changes
Tried to compile your project with the following commands 
```
mkdir build
cd build
cmake ..
make
```
and got this error:
```
CMake Error at CMakeLists.txt:4 (target_sources):
  Cannot specify sources for target "Chess" which is not built by this
  project.
```

2024-07-17 06:39 UTC, excellenteam-scaleup requested changes
I can't compile your code.
Make sure you have `CMakeLists.txt` file and that you can compile your code with the following commands: 

```
mkdir build
cd build
cmake ..
make
```
Fix it as soon as possible.

2024-07-17 14:13 UTC, SalehNaamneh commented
Ok, I will do that.

On Wed, 17 Jul 2024 at 9:40 excellenteam-scaleup ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I can't compile your code.
> Make sure you have CMakeLists.txt file and that you can compile your code
> with the following commands:
>
> mkdir build
> cd build
> cmake ..
> make
>
> Fix it as soon as possible.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Scaleup-Excellenteam/exercise-1-chess-SalehNaamneh/pull/1#pullrequestreview-2182018450>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWXF3X6E4BZPZIYYXQ6YO63ZMYGUNAVCNFSM6AAAAABJMOHZN6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCOBSGAYTQNBVGA>
> .
> You are receiving this because you authored the thread.Message ID:
> <Scaleup-Excellenteam/exercise-1-chess-SalehNaamneh/pull/1/review/2182018450
> @github.com>
>

2024-07-17 14:14 UTC, merged

2024-07-17 14:28 UTC, SalehNaamneh commented
cd Chess
mkdir build
cd build
cmake ..
cmake --build . --config Release
this is the following steps

2024-07-29 02:38 UTC, excellenteam-scaleup reviewed
Nice job, I’ve added some comments

Your code contains lots of nested `if` statements in your code, try to re-think your implementation

Good luck!

2024-07-29 02:38 UTC, excellenteam-scaleup commented on Chess/src/Bishop.cpp
> +std::vector<std::pair<int, int>> Bishop::PieceMoves() const {
Why do you need to calculate all the possible moves instead of checking that the one move that the player is trying to play is valid?

2024-07-29 02:38 UTC, excellenteam-scaleup commented on Chess/src/Bishop.cpp
> +    return 'b';
Can you think of a more generic way to know if it's black or white?

2024-07-29 02:38 UTC, excellenteam-scaleup commented on Chess/src/GameLogic.cpp
> +                PlaceAsInteger.first = ((ch - 'A') * 2) + 3;
All the special strings should be in consts for better readability and understanding of the code.

2024-07-29 02:38 UTC, excellenteam-scaleup commented on Chess/src/GameLogic.cpp
> +            return 12;
Don't use hardcoded values, it will be better to use an `Enum` and give the return values meaningful names. It will make the code more readable.

2024-07-29 02:38 UTC, excellenteam-scaleup commented on Chess/src/GameLogic.cpp
> +    for (int i = 1; i <= 8; i++) {
`8` is a ["magic number"](https://medium.com/@samaddico/programming-and-magic-numbers-f766e0cd1369), and moving it to a const will make the code more readable :) 
Also, for constants like this use `constexpr` - [Read more here](https://learn.microsoft.com/en-us/cpp/cpp/constexpr-cpp?view=msvc-170#constexpr-variables).

2024-07-29 07:34 UTC, SalehNaamneh commented
Thank you for addressing some improvements
The enum thing I tried to do it
And i did it in the second part
In this part the time was tight I didn’t polish it very will

Thank you for your concerns